# Generated by Django 4.2 on 2023-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
            ],
        ),
    ]
