# Generated by Django 4.1.8 on 2023-04-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_mapping_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMapping',
        ),
    ]
